# Generated by Django 4.2.7 on 2025-03-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(max_length=12, unique=True, verbose_name='phone'),
        ),
    ]
